### ISSUE TITLE
Add a phylogeny context

### ISSUE THREAD

**Issue by SimonMorvan** [DataDrivenEcologicalSynthesis/MostMisidentifiedSpecies#16]
Could we could include a phylogeny information?

ex: For a genus that contains many species, it is more likely for identifiers to confuse one species for another. Vs. a Genus with only one species?

-> Find number of species per genus.

**Comment by vcameron1** [comment]
Interesting analysis avenue!

But I think we still need first to define what a misidentified species is and find them using iNaturalist data. Then compare species we found to # related species.

**Comment by jadedaws** [comment]
Brenda found number of species per genus from GBIF and joined with iNat data
