### ISSUE TITLE
Agreement on higher taxonomic rank (genus / family)

### ISSUE THREAD

**Issue by SimonMorvan** [DataDrivenEcologicalSynthesis/MostMisidentifiedSpecies#17]
Can we report taxa for which the identifications never reach species level ?

**Comment by vcameron1** [comment]
Great idea to pinpoint genus or higher taxonomic levels that may cause problem to ID, but there is no ways to identify specific species that way...

**Comment by jadedaws** [comment]
Settled on species level identification as it contains 68% of all disagreed upon observations
