### ISSUE TITLE
GBIF Data Script

### ISSUE THREAD

**Issue by fendabenda** [DataDrivenEcologicalSynthesis/MostMisidentifiedSpecies#29]
It appears that many of the observations in the api data were not made at the genus level, but at a different taxonomic level. In cases where the subgenus name is used, these will be replaced by the corresponding genus names, in order to match with a list of genera for the species-per-genus analysis.

**Comment by jadedaws** [comment]
Brenda worked around the difficult species naming from the GBIF data
